# This workflow automatically creates monthly releases
# It locks dependencies, updates the version to the current date,
# and publishes to PyPI with calendar versioning (YYYY.MM.patch)his workflow automatically creates monthly releases
# It locks dependencies, updates the version to the current date,
# and publishes to PyPI with calendar versioning (YYYY.MM)
#
# Copyright (c) 2025 MeteoSwiss, created by Hugues de Laroussilhe; hugues.delaroussilhe@meteoswiss.ch

name: CI_publish

on:
  schedule:
    # At 03:00 on day-of-month 1.
    - cron: '0 3 1 * *'
  workflow_dispatch:  # Allow manual triggering

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry and python package
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Update version to current date
      run: |
        YEAR_MONTH=$(date -u +%Y.%-m)
        git fetch --tags

        # Find the highest patch version for this month
        LATEST_PATCH=$(git tag -l "${YEAR_MONTH}.*" | sed "s/${YEAR_MONTH}\.//" | sort -n | tail -1)
        if [ -z "$LATEST_PATCH" ]; then
          PATCH=0
        else
          PATCH=$((LATEST_PATCH + 1))
        fi

        VERSION="${YEAR_MONTH}.${PATCH}"
        echo "New version: $VERSION"
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
        sed -i "s/^.. |release_version| replace:: .*/.. |release_version| replace:: $VERSION/" README.rst
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Generate lock file
      run: |
        # Update only Anemoi packages and their dependencies
        poetry update anemoi-datasets anemoi-graphs anemoi-inference anemoi-models anemoi-registry anemoi-training anemoi-utils
        poetry install

    - name: Update changelog with package versions
      run: |
        python scripts/update_changelog.py

    - name: Commit changes
      run: |
        git add pyproject.toml poetry.lock CHANGELOG.rst README.rst
        git commit -m "monthly release ${{ env.RELEASE_VERSION }}" || echo "No changes to commit"

    - name: Create and push tag
      run: |
        git tag -a "${{ env.RELEASE_VERSION }}" -m "Release ${{ env.RELEASE_VERSION }}"
        git push origin main
        git push origin "${{ env.RELEASE_VERSION }}"

    - name: Publish to TestPyPi
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.TESTPYPI_API_TOKEN }}
        poetry publish --build -r testpypi
        rm -rf dist/

    - name: Publish to PyPi
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry publish --build

    - name: Build documentation
      run: poetry run sphinx-build doc doc/_build

    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3

      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/
        force_orphan: true
