# This workflow will install Python dependencies and run tests with a variety of Python
# versions. For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Adapted from: https://github.com/actions/starter-workflows/blob/master/ci/python-package.yml
#
# Copyright (c) 2025 MeteoSwiss, created by Hugues de Laroussilhe; hugues.delaroussilhe@meteoswiss.ch

name: CI_test

on:
  pull_request:
    branches: '**'
  push:
    branches: ['main']
  workflow_call:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']


    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Install dependencies
      run: poetry install
